<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NiiRMotion.Core\NiiRMotion.Core.csproj" />
    <ProjectReference Include="..\NiiRMotion.Infrastructure\NiiRMotion.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\niirmotion.ico" />
    <Resource Include="Assets\niirmotion-icon.png" />
    <Resource Include="Assets\Fonts\InterVariable.ttf" />
    <Content Include="Assets\Fonts\Inter-LICENSE.txt" CopyToOutputDirectory="PreserveNewest" />
    <Resource Include="Assets\device-*" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\niirmotion.ico</ApplicationIcon>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
  </PropertyGroup>

</Project>
